name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn clean install

    - name: Verify JAR file exists
      run: |
        if [ ! -f target/demo-0.0.1-SNAPSHOT.jar ]; then
          echo "JAR file not found!"
          exit 1
        fi

    - name: Build Docker image
      run: docker build . -t hernangrillo/my-app:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push hernangrillo/my-app:${{ github.sha }}

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{"branch":"master"}' \
        https://api.render.com/v1/services/srv-cqfc01t6l47c73bbost0/deploys
